### ISSUE TITLE
Why does flextable automatically make numeric values go to the thousandth place?

### ISSUE THREAD

**Issue by eeldren** [davidgohel/flextable#118]
I noticed that the automatic behavior of flextable is to make numeric values go to the thousandth place - whether that means adding more 0s or cutting numbers off.

For example:

`flextable::regulartable(data.frame(A = c(1, 2.2322), B = c(3, 4.2)))`

Creates the following:

![Screen Shot 2019-05-03 at 6 20 47 PM](https://user-images.githubusercontent.com/18270404/57168544-32896100-6dd0-11e9-8d88-f6dfc8632e51.png)

I found that this can be altered using the `colformat` cols but this seems really unnecessary compared to flextable just outputting what initially exists in the data.frame and allowing users to change them from there.

For example, we use flextable (though previously used ReporteRs) to build up an internal package that anyone can use to output their table in a set format. To have this work, we need our functions to be fully dynamic and flexible. As such, having this feature where it automatically goes to the thousandth place is much more difficult than just having flextable output what it's given.

Is there a reason that this is the default action and if not, is there any chance for it to be changed?

**Comment by davidgohel** [comment]
> I found that this can be altered using the colformat cols but this seems really unnecessary 
compared to flextable just outputting what initially exists in the data.frame and allowing 
users to change them from there.
> [...]
Is there a reason that this is the default action and if not, is there any chance for it to be changed?

Discalimer: it ends with **Yes, there are reasons.**

I appreciate your feedback here. I understand there are two subjects, please clarify if 
I am wrong. 

1. You don't want to write any code (except `flextable`) to produce a formatted table. 
   The format you want is the same than `print.data.frame`.
2. You think that `colformat_*` (and maybe other functions) are not necessary.

-------

About the first point. As you said, this is not the default. I understood you are 
in a team of R users and you have an internal package, I suggest you to add a function 
in your internal package that does the job and to replace your calls to `flextable` by 
calls to your function:

```{r}
eeldren_ft <- function(x){
  z <- format(x, digits = NULL, na.encode = FALSE)
  z <- flextable(z)
  autofit(z)
}
dat <- head(iris)
print(dat)
eeldren_ft(head(iris))
```

```
##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa
```

<img width="403" alt="Capture d’écran 2019-05-04 à 11 42 20" src="https://user-images.githubusercontent.com/4331618/57177164-c22b2000-6e61-11e9-9ab1-ceeb07311e4e.png">


There are reasons for these default values, I tried to find rules and advices, I used a lot 
my customer feedbacks (from life science and also from other sectors) and I used Claus O. Wilke 
recommandations that can be read here: 
https://serialmentor.com/dataviz/figure-titles-captions.html#tables

In summary, it's better to right align numeric columns and to format them with the same 
number of digits after the decimal. The default 3 digits have been choosen because : 

* 4 is too much
* 1 and 2 is not enough for some users than wanted to at least see by 
  default p value significant numbers

Can you please provide your rules? It seems different sectors have different rules. 
Those defined in life sciences are my favorites as they are *defined*.


------

About the second point. These functions are answering a need that is important for other users. 

For example, let's try to make a model report with broom.

```{r}
library(flextable)
library(broom)
library(magrittr)
a <- aov(mpg ~ wt + qsec + disp, mtcars)
df <- tidy(a)
df
```

```
## # A tibble: 4 x 6
##   term         df     sumsq    meansq  statistic   p.value
##   <chr>     <dbl>     <dbl>     <dbl>      <dbl>     <dbl>
## 1 wt            1 848.      848.      121.        1.08e-11
## 2 qsec          1  82.9      82.9      11.9       1.82e- 3
## 3 disp          1   0.00102   0.00102   0.000147  9.90e- 1
## 4 Residuals    28 195.        6.98     NA        NA
```

With flextable package, you can easily make a nice report table from the broom output 
(when I say easily, I understand you don't agree with that ;) and I will probably 
add sugar functions soon or later): 

```{r}
p_val_format <- function(x){
  z <- scales::pvalue_format()(x)
  z[!is.finite(x)] <- ""
  z
}
flextable(df) %>% 
  set_formatter(values = list("p.value" = p_val_format) ) %>% 
  colformat_int("df", suffix = " dof") %>% 
  # more cosmetics
  set_header_labels(term = "Term", df = "",
                    "sumsq" = "Sum of squares", 
                    meansq = "Mean squared error", 
                    statistic = "Statistic", p.value = "p-value"
                    ) %>% 
  autofit()
```

<img width="530" alt="Capture d’écran 2019-05-04 à 11 44 10" src="https://user-images.githubusercontent.com/4331618/57177185-f7377280-6e61-11e9-9de1-9f9ec58b90d4.png">


In the above example, I used `set_formatter` as I wanted to control a specific formatting 
not available in `flextable`; I also used `colformat_int` to make sure the floating values 
are displayed as integer (as they should be) and I added a suffix. 

Adding a step of data preparation that transform all values to character values 
only for reporting purpose is not the way I want to work. Having these API allows me to 
use other functions (from package `scales` for example), I can also create specific `theme` functions 
to gather some specific needs into a single function.

These functions are also very useful for conditional formatting: 

```{r}
flextable(df) %>% 
  set_formatter(values = list("p.value" = p_val_format) ) %>% 
  color(i = ~ p.value > .05, color = "#DFDFDF") %>% 
  autofit()
```

<img width="434" alt="Capture d’écran 2019-05-04 à 11 44 52" src="https://user-images.githubusercontent.com/4331618/57177190-0e766000-6e62-11e9-974d-ef24aef0e387.png">


If you change the data.frame columns as character column before using flextable, you could not easily 
do these operations. You would probably end with something like `as.numeric` which is weird to me as 
you may loose precision and it makes the code less readable:

```{r}
df2 <- format(df, digits = NULL, na.encode = FALSE)
flextable(df) %>% 
  color(i = ~ as.numeric(p.value) > .05, color = "#DFDFDF") %>% 
  autofit()
```
