### ISSUE TITLE
Aspect ratio does not update to make tables larger in RStudio Viewer

### ISSUE THREAD

**Issue by eeldren** [davidgohel/flextable#119]
My team has been finding that the aspect ratio for the tables will update column width to accommodate a smaller RStudio Viewer window size:

![Screen Shot 2019-05-03 at 4 51 02 PM](https://user-images.githubusercontent.com/18270404/57165029-f6500380-6dc3-11e9-9f1a-3bf8ac458491.png)

![Screen Shot 2019-05-03 at 4 51 11 PM](https://user-images.githubusercontent.com/18270404/57165043-f8b25d80-6dc3-11e9-9273-d127e29ed5f9.png)

But it won't update the table size to make the columns wider:

![Screen Shot 2019-05-03 at 4 54 03 PM](https://user-images.githubusercontent.com/18270404/57165076-12ec3b80-6dc4-11e9-8d85-dbda9dde0560.png)

Previously, ReporteRs was able to make the columns wider just by expanding the Viewer pane, which was actually quite critical for our team as we will often output directly from the RStudio viewer into a .jpg file. By not being able to expand the column width, we end up having to go through many extra steps to get all the tables to be the same size columns (e.g., copy-pasting into a Google Doc, expanding the columns there, and then screenshotting and saving the screenshot as a .jpg).

This is different from just specifying column widths because we often have different numbers and types of columns and so don't know how wide they should be to be the same width, but we do know the overall pixel width that the table needs to be when outputting from the Viewer.

Is this something that could be added?

**Comment by davidgohel** [comment]
> My team has been finding that the aspect ratio for the tables will update column width to accommodate a smaller RStudio Viewer window size: [...] But it won't update the table size to make the columns wider.


Column width is not updated (columns width are defined by flextable). You can read about that here :

https://davidgohel.github.io/flextable/articles/overview.html#flextable-keypoints

https://davidgohel.github.io/flextable/articles/layout.html#cell-widths-and-heights

The RStudio viewer is not changing aspect ratio when resizing on my computer - if you don't have the 
same rendering, this is probably because you are using a windows platform. (and RStudio viewer on windows is/was not behaving the same way modern browser do, I think there are new things in the latest version). 

-----------

Yes, ReporteRs do not define column width when output format is HTML. It must for Word and PowerPoint outputs.

If that is again a critical point for you, you should improve your process. For example, use a function to produce an image. It would use package `webshot`. Below a draft (you can of course adapt it to your need):


```
as_image <- function(x, file, do_autofit = TRUE){
  
  if (!requireNamespace("webshot", quietly = TRUE)) {
    stop("package webshot is required when saving a flextable as an image.")
  }
  if( do_autofit )
    x <- autofit(x) # see ?autofit


  tf <- tempfile(fileext = ".html")
  save_as_html(x = x, path = tf)

  webshot::webshot(url = sprintf("file://%s", tf), file = file, selector = "body > table", zoom = 3, expand = 10 )
}
```

I have no idea of what is your real context so it's hard to provide a better help. 

I will add `as_image` soon. I may implement a version with no column widths later.

**Comment by davidgohel** [comment]
I implemented new functions that should help:

* `flextable_dim` to get width, height and aspect ratio of a flextable, read more here 
https://davidgohel.github.io/flextable/reference/flextable_dim.html
* `plot` to display a flextable in an R plot, read more here https://davidgohel.github.io/flextable/reference/plot.flextable.html
* `save_as_image` to save the flextable as an image, read more here https://davidgohel.github.io/flextable/reference/save_as_image.html

KR
