### ISSUE TITLE
remove phantomJS dependency?

### ISSUE THREAD

**Issue by randomgambit** [davidgohel/flextable#132]
Hello there!

Thanks for this wonderful package. The `phantomJS` dependency is now deprecated and we should probably find another alternative to save as image. This is related to a similar issue in `kable`.

https://github.com/haozhu233/kableExtra/issues/392
What do you think?
Thanks!

**Comment by davidgohel** [comment]
Hello,

In issue 75 of webshot, one of the authors is saying they are working on it so let's just wait for news. For now, it works well. 

There are alternatives, one is JavaScript, other is chrome headless, ... I am not worry about that :)

KR
David

**Comment by randomgambit** [comment]
thanks but the issue is that in many corporate settings, one cannot install external dependencies like phantomJS...

**Comment by davidgohel** [comment]
I am installing phantomJS in corporate environnements, but yes, sometimes users are not allowed to do so.  It often has to be done with agreement of IT team.

If you want other options: 

* you have javascript (need node.js so same issue for you than with phantom.js), 
* headless chrome CLI (need chrome so same issue for you than with phantom.js)
* Selenium (I think it needs java which is now forbidden is many corporate env.)
* ???

There are two points in your question: 

* **you can't install external programs**. Replacing phantomJS by headless chrome or node or any other external program will not solve that issue. I don't know how to do it without external program.
* **phantomJS is deprecated.** I won't work on that because RStudio is already working on it. Let's wait. 

For now, package `webshot` works as expected and in issue 75 they say they will "eliminate the need for PhantomJS".
