### ISSUE TITLE
Add equivalent of "escape = FALSE"

### ISSUE THREAD

**Issue by dmurdoch** [davidgohel/flextable#156]
The `kable()` function in `knitr` has an argument `escape` that defaults to `TRUE`, which tells `kable` to escape any raw HTML/LaTeX in the table.  It would be nice to have such an option in `flextable` as well, to solve problems like this one:  https://stackoverflow.com/q/58220735/2554330, where the poster wants to put a superscript or subscript into the cell text.

One way to support superscripts/subscripts would be to allow math expressions using the `plotmath` approach from the `graphics` package, but that would be a huge amount of work.  A much simpler approach is just to allow raw HTML in the cell.  For example,

    tab <- data.frame(x = "10<sup>-3</sup>")
    flextable(tab)

currently escapes the angle brackets and displays text `10<sup>-3</sup>` in the cell.  It would be nice to be able to say

    flextable(tab, escape = FALSE)

and have the cell displayed with a superscript.

This works if the `htmlEscape` call is removed here:  https://github.com/davidgohel/flextable/blob/f1fc70a380bf553509d5b79c1b8edb7cdc320383/R/01_fpstruct.R#L796.  I would put together a PR, but I'm not familiar enough with the internals to know how to pass the `escape = FALSE` value into this location, or where else edits should be made.

**Comment by davidgohel** [comment]
Thanks for your comment.

Beeing able to write sub/sup text is already possible, there are *sugar* functions for that (https://davidgohel.github.io/flextable/articles/display.html#sugar-functions-for-complex-formatting). 

I am a little annoyed by this. I know users want to add latex equation but all solutions are quite expensive in term of time. One important point is I tried to provide a single API to output HTML, Word and PowerPoint, allowing this would break this and users would ask for this with docx/pptx outputs (which is clearly complicated because of MS formats).

In the SO, it is asked to change the paradigm so that table content is automatically transformed. But flextable idea was to leave data as they are and let users specify the display content with R function `flextable::compose`. 

I can add an option but I am sure I will regret that when later users will ask why it does not work with Word or PowerPoint output.

**Comment by dmurdoch** [comment]
Thanks for pointing out this solution, it works.  The only additional suggestion I'd make is that `as_paragraph` try to run `as.character()`:  I got an error with this code:

    as_paragraph(10, as_sup(-3))
    # Error in as_paragraph(10, as_sup(-3)) : 
    # argument ... should only contain objects of class 'chunk'.

whereas this works:

    as_paragraph("10", as_sup("-3"))

and this produces the desired result.

**Comment by davidgohel** [comment]
Thanks, that's better with your suggestion!

```
library(flextable)
bab <- data.frame(x = "dummy")
bab <- flextable(bab)
bab <- compose(bab, part = "body", i = 1, j = 1,
               value = as_paragraph(10, as_sup(-3)))
bab
```

<img width="93" alt="Capture d’écran 2019-10-05 à 14 30 23" src="https://user-images.githubusercontent.com/4331618/66254862-b0d1a100-e77c-11e9-8c28-1e9e566ea78f.png">
