### ISSUE TITLE
rotate does not work with LaTeX-PDF output

### ISSUE THREAD

**Issue by neuwirthe** [davidgohel/flextable#157]
The following code rotates and merges the `head_col` values when producing html output in RStudio, but it does not rotate when producing pdf output (via LaTeX). 

```
library(dplyr)
library(flextable)
my_df <- tibble(
  head_col = rep("head_col",5),
  num_col = 1:5 
)

my_df %>%
  flextable() %>%
  rotate(1:5,1,rotation="tbrl",part="body") %>% 
  merge_v(1) 
```

**Comment by davidgohel** [comment]
Could you share a reproducible example? I don't know how you produced the pdf

**Comment by neuwirthe** [comment]
I assume this contains everything you need (including sessionInfo)

[rotate_problem.pdf](https://github.com/davidgohel/flextable/files/3717228/rotate_problem.pdf)


[rotate_problem.Rmd.zip](https://github.com/davidgohel/flextable/files/3717232/rotate_problem.Rmd.zip)


[rotate_problem.html.zip](https://github.com/davidgohel/flextable/files/3717234/rotate_problem.html.zip)

**Comment by RABxx** [comment]
For me I cannot get any rotate usage to work. Even in the examples in the documentation nothing is rotated :(

**Comment by neuwirthe** [comment]
Did you produce html?

**Comment by RABxx** [comment]
Nope, just viewed in RStudio, where there was no change. Just tried outputting to Word though, and it was rotated... why doesn't it show in RStudio?

**Comment by davidgohel** [comment]
The rotation in HTML is a difficult point, this is mentioned here: https://davidgohel.github.io/flextable/articles/format.html#text-rotation

This issue is related to a webshot issue (behind the scene phantome.js is doing the screenshot but some formattings are lost during the process). This is solved by using other solution (crrri, webshot2) but none of them are on CRAN. I will try to find a solution in the next dev run.

**Comment by davidgohel** [comment]
I think it is ok now. 

* The rotation is now ok with HTML (which is used when output is pdf). 
* PDF will render rotation only if the chunk option `webshot="webshot2"`  (you need to install webshot2 https://github.com/rstudio/webshot2)

In your example, you also need to call `fix_border_issues` (to fix border issues caused by cells merging).

----


```````

---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, webshot="webshot2")
```

## With your code


```{r}
library(dplyr)
library(flextable)
my_df <- tibble(
  head_col = rep("head_col",5),
  num_col = 1:5 
)

my_df %>%
  flextable() %>%
  rotate(1:5,1,rotation="tbrl",part="body") %>% 
  merge_v(1) %>% 
  fix_border_issues()
```



## Another example 

```{r}
library(flextable)

ft <- flextable(head(iris))

# measure column widths but only for the body part
w_body <- dim_pretty(ft, part = "body")$widths
# measure column widths only for the header part and get the max
# as height value for rotated text
h_header <- max( dim_pretty(ft, part = "header")$widths )

ft <- rotate(ft, j = 1:4, rotation="btlr",part="header")
ft <- rotate(ft, j = 5, rotation="tbrl",part="header")

ft <- valign(ft, valign = "center", part = "header")
ft <- align(ft, align = "center", part = "all")

# Manage header height
ft <- height(ft, height = h_header * 1.1, part = "header")
# ... mainly because Word don't handle auto height with rotated headers
ft <- hrule(ft, i = 1, rule = "exact", part = "header")

ft
```


```````

[Untitled.pdf](https://github.com/davidgohel/flextable/files/4130993/Untitled.pdf)


<img width="1044" alt="Capture d’écran 2020-01-29 à 23 16 56" src="https://user-images.githubusercontent.com/4331618/73402400-7d97bc80-42ed-11ea-97d1-853e75701c5d.png">
