### ISSUE TITLE
How to use `bookdown` references in RMarkdown with flextable?

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/flextable#169]
Hi David,

I'm highly relying on `flextable` to create tables with beautiful headers, and I'm used to use it along with `officer` to create word documents.

However, I now have to use RMarkdown for a specific project that relies on bookdown to link tables numbers.

Here is a reproducible example of expected output:

```
---
title: "Iris"
output_file: "test.docx"
output: bookdown::word_document2
---
Table iris is given in Table \@ref(tab:iris).

```{r iris, echo=FALSE, results='asis', message = FALSE, warning = FALSE, error=FALSE, tidy = FALSE}
    knitr::kable(head(iris), booktabs = T, caption  = "Characteristics of patients")
\```

```
![image](https://user-images.githubusercontent.com/15105152/70143055-ecb0b600-169a-11ea-835e-a995afb111d3.png)

I'd like to achieve this with a `flextable` instead of a `dataframe` (`flextable(head(iris))` for instance), but `kable` won't take a `flextable` as input.

I use [knit_print](https://davidgohel.github.io/flextable/reference/knit_print.flextable.html) as the help suggests, which print the table perfectly but won't create a table 1 reference, so `\@ref` will not be found.

Is there a way to make this work?

**Comment by DanChaltiel** [comment]
I found a workaround for this issue:
```
---
title: "Iris"
output: bookdown::word_document2
---
Table iris is given in Table \@ref(tab:irisTable).

```{r description, echo=FALSE, results='asis', message = FALSE, warning = FALSE, error=FALSE, tidy = FALSE}
cat("<caption> (\\#tab:irisTable) Table Iris </caption>")
flextable(head(iris))
``'

```

It might be worth it to add a function that automates this process.

This workaround is working at least for my session:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)
Matrix products: default
locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252 
```

**Comment by DanChaltiel** [comment]
Of note, there might be a minor issue with `flextable:::knit_print.flextable`: 

```
```{r, echo=FALSE, results='asis'}
cat("<caption> (\\#tab:irisTable) Table Iris </caption>")
flextable(head(iris))
cat('\n')
cat("<caption> (\\#tab:irisTable2) Table Iris aussi</caption>")
flextable(head(iris))
`'`
```

This chunk works fine, but will not if you remove the `cat('\n')` line.

This problem disappears if you od not use captions.

**Comment by mbojan** [comment]
Whoah! @DanChaltiel you made my day with the workaround! Thanks! 
Still, I hope this, or a perhaps some other solution, will get integrated into the package properly.

**Comment by davidgohel** [comment]
@DanChaltiel I am working (on officer side) to enable nice word references that should then be available for flextable (but not only...)

**Comment by DanChaltiel** [comment]
@davidgohel By the time, I got to that function, if it can be any help:

```
#' Add a table legend
#'
#' @param x a docx object
#' @param legend the table legend
#' @param legend_style may depend on the docx template
#' @param style the legend style (strnog, italic...)
#' @param seqfield to figure this out, in a docx file, insert a table legend, right click on the inserted number and select "Toggle Field Codes". This argument should be the value of the field, with extra escaping.
#'
#' @export
body_add_table_legend = function(x, legend, legend_style="table title", style="strong", 
                                 seqfield="SEQ Table \\* Arabic"){
  x %>% 
    body_add_par(value=legend, style=legend_style) %>% 
    slip_in_text(str=": ", style=style, pos="before") %>% 
    slip_in_seqfield(str=seqfield, 
                     style=style, pos="before") %>% 
    slip_in_text(str="Table ", style=style,
                 pos="before") %>%
    identity
}
```

I'm using it and it works like a charm to build table summaries, but I did not figure out yet how to reference the legend in a paragraph.

I think the best way for this would be to be able to directly reference legends in a `body_add_par` with some pseudo-tag, but this may require diving a little too deep into the code for me right now.

**Comment by davidgohel** [comment]
@DanChaltiel thanks, this will be close to your solution :) I think there will be a function for *legend* named `block_caption` and a function for *references* (`run_reference`)

**Comment by atusy** [comment]
I implemented `ftExtra::loves_bookdown` which supports cross-referencing with bookdown.
Once this function is run in the any place of Rmd file, cross reference works both for docx and html.

https://github.com/atusy/ftExtra/

## Reproducible Example

````
---
output:
    bookdown::word_document2: null
    bookdown::html_document2: null
---

```{r setup}
library(flextable)
library(ftExtra)
loves_bookdown()
```

Referencing table \@ref(tab:iris).

```{r}
iris %>% head %>% as_flextable %>% set_caption('(\\#tab:iris) A caption with table number.')
```
````

## How does it work?

As @DanChaltiel mentioned https://github.com/davidgohel/flextable/issues/169#issuecomment-565407338, table caption needs be wrapped by `<caption>` tag.

### HTML

For HTML, table caption is by default wrapped by `<caption>` tag, but cross-referencing resolver is avoided because flextable's HTML code is wrap by `<!--html_preserve-->` and ` comments.

Thus, I unpreserve the `<caption>` by `knitr::knit_hooks`.
For example,

```html
<!--html_preserve--><some tags><caption>table caption</caption><more tags><!--/html_preserve-->
```

becomes

```html
<!--html_preserve--><some tags><!--/html_preserve--><caption>table caption</caption><!--html_preserve--><more tags><!--/html_preserve-->
```

### Word (docx)

For docx, table caption in the intermediate md file is like

```md
::: {custom-style="Table Caption"}

(\#tab:foo) foo

:::
```

There is no `<caption>` tag.
So I added it like

```md
::: {custom-style="Table Caption"}

<caption>(\#tab:foo) foo</caption>

:::
```

This is hacky, but I guess it is okay because Pandoc ignores HTML tags when output format is not HTML.

## Direct implementation in flextable package

Due to the high demand, I'm considering to implement this feature directly in flextable.
Currently, the feature is implemented via `knit_hooks`, but I want to implement via `knit_print` method so that users does not have to run an extra function when output is bookdown format.
At the same time, I am considering automatically label captions based on chunk label just like `kable`.
What do you think @davidgohel ?
If you like my idea, I'd be happy to work on PR.

Related issues: https://github.com/davidgohel/flextable/issues/193, https://github.com/rstudio/bookdown/issues/746, https://github.com/rstudio/bookdown/issues/659

**Comment by davidgohel** [comment]
@atusy I like your idea, thanks for your work. I was planning to work on it but you seem to have clear idea on the subject (I don't yet), so go for it :)

**Comment by atusy** [comment]
@davidgohel Thanks! I will!!

**Comment by davidgohel** [comment]
implemented via #205

**Comment by CarolineXGao** [comment]
Hi Dan, 

This code works with word, thanks!!  But it seems bookdown pdf cannot get the table number correctly.  Latex seems to be picking up tab:irisTable, but just not giving it a number. Am I missing something? 


Table iris is given in Table \@ref(tab:irisTable).

```{r description, echo=FALSE, results='asis', message = FALSE, warning = FALSE, error=FALSE, tidy = FALSE}
cat("<caption> (\\#tab:irisTable) Table Iris </caption>")
flextable(head(iris))
```

Thanks!!!!

Caroline

**Comment by dar143** [comment]
Seems like the se of flextables set_caption breaks the standard referencing link when rendering to word.

```
output:
  bookdown::word_document2
```
This works 

This is a linked reference to Table \@ref(tab:airtable), its number is computed by markdown 
    and it's linked to the corresponding table when clicking on it.
   
```
```{r airtable, ft.align = "left", echo = TRUE}
air_tab <-head(airquality) %>%
  flextable() %>% 
  autofit()  %>%
  color(part = "header", color = "white") %>%
  bg(part = "header", bg = "black") %>%
  fontsize(part = "all", size = 9)# %>%
#  set_caption("Example table of data frame", style = "table")
air_tab
```
```

But this doesn't

```
```{r airtable, ft.align = "left", echo = TRUE}
air_tab <-head(airquality) %>%
  flextable() %>% 
  autofit()  %>%
  color(part = "header", color = "white") %>%
  bg(part = "header", bg = "black") %>%
  fontsize(part = "all", size = 9)# %>%
  set_caption("Example table of data frame", style = "table")
air_tab
```
```

Does the set_caption function define a new table references link?

Thanks
Ross

**Comment by davidgohel** [comment]
@dar143  

> Does the set_caption function define a new table references link?

No. Also, you did  not set any bookmark id, the package won't guess you want it to be bookmarked "airtable".

@CarolineXGao this is not the way it should be used. Please have a look at https://ardata-fr.github.io/flextable-book/captions-and-cross-references.html#captions

To all, open a **new issue** if you think you found a bug. This issue is closed.
