### ISSUE TITLE
Table autonumber in bookdown

### ISSUE THREAD

**Issue by dmenne** [davidgohel/flextable#193]
I have posted a comment on 

https://community.rstudio.com/t/table-numbering-in-bookdown-why-can-only-kable-do-it-portably-huxtable-pander-flextable-fail/54313

showing how `knitr::kable` nicely autonumbers tables in bookdown documents for HTML and Word, while `huxtable and pander` fail for both and `flextable` only works with HTML. I might have used some examples wrongly, so please feel free to correct me.

**Comment by davidgohel** [comment]
This will be a feature soon for HTML and Word :)

**Comment by dmenne** [comment]
Thanks, I had read about it on some thread and therefore had downloaded from github, so I was surprised it did not work.

**Comment by davidgohel** [comment]
Can you give the link? I did not communicate about it...

**Comment by dmenne** [comment]
https://community.rstudio.com/t/table-numbering-in-bookdown-why-can-only-kable-do-it-portably-huxtable-pander-flextable-fail/54313

**Comment by dmenne** [comment]
Sorry, lost it. I remember it was on SO and the guy was called david gohel or the like .-)

**Comment by davidgohel** [comment]
Table autonumber in bookdown is available since few commits. See #205

Also now, it is possible to use MS Word auto-numbering feature (if not in a bookdown context, it means the following has no effect in a bookdown project):

Function `set_caption` has now more arguments:

```
set_caption(x, caption, autonum = NULL, ref = NULL, style = "Table Caption",...)
```

* `autonum` is an object returned by `officer::run_autonum()`
* `ref` is an id that will be used to bookmark the caption (useful for cross references)
* `style` the Word paragraph style to use

It works with Word output made by 

1. `rmarkdown::render(output = "word_document")`
2. `body_add_flextable` and officer


## Illustration

<img width="818" alt="Capture d’écran 2020-04-16 à 19 47 28" src="https://user-images.githubusercontent.com/4331618/79489125-21eeec80-801b-11ea-91ab-2689b1476872.png">



<img width="1669" alt="Capture d’écran 2020-04-16 à 19 44 48" src="https://user-images.githubusercontent.com/4331618/79488954-dccaba80-801a-11ea-8604-afb111821525.png">


```````````````
---
title: "flextable example"
output: "word_document"
---

```{r setup, include=FALSE}
library(knitr)
library(flextable)
library(magrittr)
library(data.table)
library(officer)
opts_chunk$set(echo = FALSE, message = FALSE)

autonum <- run_autonum()
```

```{r}
library(scales)
colourer <- col_numeric(
    palette = c("red", "wheat", "red"),
    domain = c(-1, 1))

cor_matrix <- cor(mtcars)
mycut <- cut( cor_matrix, 
  breaks = c(-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1), 
  include.lowest = TRUE, label = FALSE)
data <- data.frame(rowname = row.names(cor_matrix), stringsAsFactors = FALSE) %>%
  cbind(cor_matrix)
```

## An example 

```{r}
flextable(data) %>%
  bg(j = colnames(cor_matrix), bg = colourer) %>%
  align(align = "center", part = "all") %>%
  compose(i = 1, j = 1, value = as_paragraph(""), part = "header") %>% 
  colformat_num(j = colnames(cor_matrix), digits = 2) %>% 
  autofit() %>% 
  set_caption("correlation matrix", autonum = autonum)
```

## Another example 

```{r}
ft <- flextable(head(iris))

# measure column widths but only for the body part
w_body <- dim_pretty(ft, part = "body")$widths
# measure column widths only for the header part and get the max
# as height value for rotated text
h_header <- max( dim_pretty(ft, part = "header")$widths )

ft <- rotate(ft, j = 1:4, rotation="btlr",part="header")
ft <- rotate(ft, j = 5, rotation="tbrl",part="header")

ft <- valign(ft, valign = "center", part = "header")
ft <- align(ft, align = "center", part = "all")

# Manage header height
ft <- height(ft, height = h_header * 1.1, part = "header")
# ... mainly because Word don't handle auto height with rotated headers
ft <- hrule(ft, i = 1, rule = "exact", part = "header")

ft %>% 
  set_caption("iris", autonum = autonum)
```

\newpage

## flextable - demo as_grouped_data

```{r}
data_CO2 <- dcast(as.data.table(CO2), 
  Treatment + conc ~ Type, value.var = "uptake", fun.aggregate = mean)
data_CO2 <- as_grouped_data(x = data_CO2, groups = c("Treatment"))

as_flextable( data_CO2 ) %>% 
  bold(j = 1, i = ~ !is.na(Treatment), bold = TRUE, part = "body" ) %>% 
  bold(part = "header", bold = TRUE ) %>% 
  width(width = 1.5) %>% 
  compose(i = ~ !is.na(conc), j = "conc", 
          value = as_paragraph(
            as_chunk(conc, formatter = function(x) sprintf("%.0f", x))
          )
  ) %>% add_footer_lines("dataset CO2 has been used for this flextable") %>% 
  bg(bg = "#FFFFFF", part = "footer") %>% 
  set_caption("mean of carbon dioxide uptake in grass plants", autonum = officer::run_autonum()) %>% 
  set_header_labels(conc = "Concentration") %>% 
  width(width = c(1.5, 1, 1))  %>% 
  set_caption("CO2", autonum = autonum)
```


```````````````

**Comment by dmenne** [comment]
Thanks. I added a comment to my gist: https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd.  I will update the gist later with an example

**Comment by dmenne** [comment]
https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd has been updated to work with flextable. 

Nice, and thanks for the long awaited feature!

**Comment by davidgohel** [comment]
You are welcome - yes, times can be difficult to find :) 

Cool, I will close the issue when the documentation will be updated and completed.

Note there is also an ongoing work on officedown to transform bookdown captions and cross-references as Word auto numbered captions and real cross-references (clic-ables). It should work with all packages that implement bookdown syntax for captions and references

**Comment by dmenne** [comment]
I am not so much in Office, so I have not tested it. It must be a hell of work to get this to work with all the docx versions around.

**Comment by davidgohel** [comment]
I know well the office format now, so I guess it's far less painful than it was few years ago :)

(reopening the issue - I will close it when documentation will be updated and completed)

**Comment by davidgohel** [comment]
Caption with flextable is documented here: 
https://davidgohel.github.io/flextable/articles/display.html#captions

**Comment by dmenne** [comment]
Thanks, works. I updated 

https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd
