### ISSUE TITLE
flextable produces very lengthy CSS

### ISSUE THREAD

**Issue by twentytitus** [davidgohel/flextable#225]
Hi David,

thanks for all your great work!

We are using flextable to generate an HTML report which is to be sent to many people by email. However, it turned out the the HTML output produced is very large (too large for email): The attached markdown report with just `flextable(iris)` produces ~650 KB of HTML on my system (without the table, it's less than 70 KB):

[flextable-filesize.txt](https://github.com/davidgohel/flextable/files/4824014/flextable-filesize.txt)

It turns out that the reason is a lot of repeated CSS.

Ideally, flextable would (provide an option to) detect that many or all cells have the same formatting and define appropriate CSS classes. An easier first step would be the option to omit defaults such as `font-style:normal` and/or use shortcuts like `border: 0`, `margin: 0`. Or a `theme_minimal` that gegenrates no CSS at all apart from the formatting explicitly defined?

In the meantime, I did the following to reduce the filesize post hoc (included here only for reference to people running into the same problem, and far from perfect):

```
compress_flextables <- function(input, output) {
  html <- readLines(input)
  is_table_line <- grepl("<table", html)
  html_tab <- html[is_table_line]

  html_tab <- gsub("font-weight:normal;", "", html_tab)
  html_tab <- gsub("font-style:normal;", "", html_tab)
  html_tab <- gsub("text-decoration:none;", "", html_tab)
  html_tab <- gsub(
    "margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;", "margin:0", html_tab)
  html_tab <- gsub(paste0(
    "padding-bottom:([0-9]*)px;padding-top:([0-9]*)px;",
    "padding-left:([0-9]*)px;padding-right:([0-9]*)px;"
  ), "padding:\\2px \\4px \\1px \\3px", html_tab)
  html_tab <- gsub("border.[^0-9]*0[^;]*;", "", html_tab)
  html_tab <- gsub("rgba(0, 0, 0, 1.00)", "black", html_tab)
  html_tab <- gsub("background-color:transparent;", "", html_tab)
  html_tab <- gsub("vertical-align: middle;", "", html_tab)
  html_tab <- gsub("font-family:'Arial';", "", html_tab)
  html_tab <- gsub(
    "rgba\\(([0-9]*), ([0-9]*), ([0-9]*), ([0-9\\.]*)\\)", "rgba(\\1,\\2,\\3,\\4)", html_tab)
  html_tab <- gsub("rgba\\(([0-9]*),([0-9]*),([0-9]*),1\\.00\\)", "rgb(\\1,\\2,\\3)", html_tab)

  html[is_table_line] <- html_tab
  writeLines(html, output)
}
```

**Comment by beatrizmilz** [comment]
Something related to that: 

the tables generated in HTML does not use the html tags for tables (such as `tr`, `td`). Instead, each cell of the table uses the html tag `<p>`. It would be better to use the right HTML tags, so it could use the proper `CSS` for tables.

If is not clear what I'm saying, please inspect the HTML generated by the following code: 
`````
---
title: "Example of html tags on packages flextable and knitr"
output: html_document
---

```{r}
library(magrittr)
library(flextable)
library(knitr)
library(kableExtra)

head(iris) %>% 
  flextable::flextable()  # generate a table with flextable

head(iris) %>% 
  knitr::kable() %>% 
  kableExtra::kable_styling() # generate a table with knitr and kableExtra
```

`````

Thank you!

**Comment by davidgohel** [comment]
@beatrizmilz AFAIK, the HTML is valid and the inline css also. This is a screenshot of the HTML generated by flextable:

<img width="721" alt="Capture d’écran 2020-08-18 à 09 37 00" src="https://user-images.githubusercontent.com/4331618/90484411-6cea4f00-e136-11ea-8c62-21d0cf3673f6.png">


Text in a paragraph, paragraph is in a cell, cell is in a row, etc. The CSS is inline and this issue is about to manage that with classes or selectors instead so the size can be reduced. This is explained here: 

https://davidgohel.github.io/flextable/articles/overview.html#getting-started

https://davidgohel.github.io/flextable/articles/display.html#usage

> It would be better to use the right HTML tags, so it could use the proper CSS for tables.

The css is set by flextable. Why are you talking about using the proper CSS for tables? I don't understand what is the problem you are having or what you are trying to do. Could you detail your issue please?

**Comment by beatrizmilz** [comment]
Hi @davidgohel ! Thank you for your explanation.

So about the detail: I'm writing my thesis with rmd/package pagedown and testing some packages for tables, because I need them to work well with HTML and word. As far as I tested, flextable generates tables that work well in both outputs (awesome, thank you for this great work). But the tables generated in html did not look really well because the content of the table uses the `p` tag (you can see in the second image that you pasted in your answer, inside the `td` uses a `p` tag aswell), so it does not uses the css coded for tables (uses for regular paragraphs).

But reading your answer, looks like I need to set the style in the code that generates the table. I'll try that!

Thank you for your time :)

**Comment by atusy** [comment]
@beatrizmilz 

You can apply special css for `p` inside `td` by `td p {margin: 0}` or something like that.
If your concern is the `style` attribute hard coded to `p`, you may remove it by JavaScript.

````
```{css, echo=FALSE}
.tabwid p {
  margin: 0;
}
```


```{js, echo=FALSE}
document.addEventListener('DOMContentLoaded', function() {
  let elements = document.querySelectorAll('.tabwid p');
  for (let e = 0; e < elements.length; e++) {
    elements[e].removeAttribute('style');
  };
});
```

```{r}
flextable::flextable(head(iris))
```
````

**Comment by beatrizmilz** [comment]
Thank you @atusy  and @davidgohel !

**Comment by davidgohel** [comment]
The new version is far better:

``` 
                 file    size
1   cran_release.html 281.47K
2 github_release.html  35.65K
```

The approach is to create css styles and use class names in tags instead of inline css. This is a very nice improvement, thanks for raising the point.

**Comment by atusy** [comment]
Yay!! Thank you, David!!

**Comment by twentytitus** [comment]
This is great news. Thank you! :)

**Comment by davidgohel** [comment]
And on CRAN now :)
