### ISSUE TITLE
Option to add break between tables when using flextable in a loop

### ISSUE THREAD

**Issue by nsandau** [davidgohel/flextable#306]
First of, thanks for this excellent package.

I have a df that I want to create multiple separate tables from using flextable inside a loop. However, using  flextable_to_rmd() results in one large table when knitting to word. 

For example, the following code results in one merged table.

```{r results='asis'}
 ft <- flextable(head(iris))
 for(i in 1:3){
 flextable_to_rmd(ft)
 }
```
The following workaround results in three separate tables.

```{r, results='asis'}
for (i in 1:3) {
  cat(knit_print(ft),"<br>")
}
```

If possible, it would be nice to have this option available directly in flextable.

**Comment by mpmarcaida** [comment]
If I may also jump-in to this, I have series of tables I created from a list in R-Markdown. I'd like to output them to a Word document and separate them into one table per page. I have a code similar to the one below:

```
```{r  echo = FALSE, message = FALSE, warning=FALSE}

library(tidyverse)
library(flextable)

my_list <- iris %>%
  group_by(Species) %>% 
  split(f = as.factor(.$Species))

for (i in 1:length(my_list)) {
  myft <- flextable(my_list[[i]]) %>%
    set_caption(paste0("Table ", as.roman(i),".\n", names(my_list[i]), ".")) %>%
    padding(padding = 1.5, part = "all")
  print(myft)
}

```
```
I get 3 tables as outputs in R-Markdown but it if I knit it to produce a Word document, I only get the flextable object info texts.

**Comment by ammaraziz** [comment]
I would like to also chime in to say this would be a great feature. I'm trying to output several tables to a pdf document. 

Thanks to @nsandau tip, I added `"\\pagebreak"` in the vector. 

P.S Great package, really love working with it.

**Comment by davidgohel** [comment]
I just added the `text_after` argument to the `flextable_to_rmd` function to allow adding any text to the produced flextable.

You can now append any text you'd like, "<br>", "\\pagebreak", `officer::to_wml(officer::run_columnbreak())`, ...



`````````

```{r results='asis'}
ft <- flextable(head(iris))
for(i in 1:3){
 flextable_to_rmd(ft, text_after = "<br>")
}
```

`````````


@mpmarcaida You can read more about flextable_to_rmd at 
https://ardata-fr.github.io/flextable-book/rendering.html#r-markdown-documents  
This should be used instead of `print`
