### ISSUE TITLE
Enable height() and hrule() functions to work with .pdf output

### ISSUE THREAD

**Issue by quantitative-ecologist** [davidgohel/flextable#324]
Good day,

First, I want to thank you very much for this amazing package. 

After looking on the internet, I found this post https://stackoverflow.com/questions/61512554/r-flextable-automatic-row-height-adjustment-hrule-not-working-for-pdf-output, where the author states that the hrule() and height() functions do not work when trying to render to a .pdf output. I run into a similar problem.

I have no problem changing the width of my table using width(). However, using the functions height() and hrule() does not change the output. It would be amazing if this could work with .pdf outputs. I also saw on the hrule() documentation that .pdf files are not mentioned (only HTML, Word, and Powerpoint).

I hope this is a true missing feature, or maybe I am missing something? Is there another way to reduce spacing between lines in a table rendered in a .pdf file?

Thank you very much.

**Comment by davidgohel** [comment]
Hi

This link is obsolete. Please refer to official documentation instead of SO posts. The documentation can be read here: https://ardata-fr.github.io/flextable-book/

The documentation about your specific issue can be read here: 
- https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#pdf-output
- https://ardata-fr.github.io/flextable-book/rendering.html#note_pdf

I won't *enable* height and hrule for PDF because as stated in the documentation, I can't, I don't know how to do - if you think it is possible, show me how to do it in latex, and I will be happy to make it possible in the package. IMO it's not possible but I am not a latex expert.

> I hope this is a true missing feature, or maybe I am missing something? 

I think you can qualify it as a true missing feature. (sorry not sure if I understood the question)

> Is there another way to reduce spacing between lines in a table rendered in a .pdf file?

To reduce space between lines, use `line_spacing`, see https://ardata-fr.github.io/flextable-book/format.html#line-spacing
