### ISSUE TITLE
Add support for paragraph and/or chunk-class objects in add_footer_lines

### ISSUE THREAD

**Issue by s14230** [davidgohel/flextable#341]
Hi, 
Firstly thank you for this superb package!  I would like to add formatting to the footnote using the ftextra package. However, currently the add_footer_lines only supports characters. There's a workaround suggested [here] :(https://github.com/atusy/ftExtra/issues/64)  . 

```r
library(flextable)
library(ftExtra)
data.frame(x = 1, y = 1) %>%
  flextable() %>%
  add_footer_lines("") %>%
  compose(1, 1, as_paragraph_md("LR $\\chi$^2^"), part = "footer")
```

 It would be easier if the paragraph and/or chunk-class objects could be used directly in add_footer_lines function. Thanks very much for your help!
 Stephen

**Comment by davidgohel** [comment]
Hi,

I have been looking at this issue, and I am not willing to do the change you are asking. First because it's a lot of work, if I do that, I also need to do it for all functions that augment/add the rows in a part:

* add_body()
* add_footer()
* add_footer_lines()
* add_footer_row()
* add_header()
* add_header_lines()
* add_header_row()

Why not using function `footnote()`? Set`ref_symbols` to "" and you will get the same effect.

```
library(flextable)
library(ftExtra)

ft_1 <- flextable(head(iris))
ft_1 <- footnote( ft_1, i = 1, j = 1,
                  value = as_paragraph_md("LR $\\chi$^2^"),
                  ref_symbols = "",
                  part = "header")
ft_1 <- autofit(ft_1)
ft_1
```

<img width="543" alt="Capture d’écran 2021-10-12 à 09 28 05" src="https://user-images.githubusercontent.com/4331618/136911127-1aa0c3e6-3e03-434a-b3a7-7956f3ef5fe2.png">

**Comment by s14230** [comment]
Thanks, it might be useful for the further development of the package. If you allow for Github sponsorship perhaps you could hire someone to help with it. Or pharma, commercial users could sponsor

**Comment by davidgohel** [comment]
thanks for the suggestion. 

I am closing the issue as I don't have any solution yet to make that shortcut possible.
