### ISSUE TITLE
flextable breaks across pages and mis-aligns a cell when using pagedown::chrome_print()

### ISSUE THREAD

**Issue by jzadra** [davidgohel/flextable#370]
I do have my knit options set `ft.shadow = FALSE`.

Sometimes a flextable will break a cell in the last column onto a new page and show it on the left side.  It seems to do this sometimes and not others depending on how many characters are in the cells.  

In the examples below, the "4,345" should be under the "Number of chemicals assessed".  And there is no reason it needs to start a new page.

Intermediate html:
![image](https://user-images.githubusercontent.com/25590353/147801850-5758966d-ffb5-449a-b594-8427be4bbe3b.png)

PDF:
![image](https://user-images.githubusercontent.com/25590353/147801821-8aa928ae-4139-4df9-83ae-44363d0d7ca3.png)

**Comment by davidgohel** [comment]
also duplicated in https://github.com/rstudio/pagedown/issues/263

**Comment by jzadra** [comment]
Why invalid?

**Comment by davidgohel** [comment]
It's invalid because it's not a valid bug report.

When you submitted the issue, there were some guidelines about how to declare issues:

<img width="1034" alt="Capture d’écran 2022-01-03 à 19 22 59" src="https://user-images.githubusercontent.com/4331618/147965595-281edd7e-c9be-4c69-8a84-91df07b60d52.png">

See source here: https://github.com/davidgohel/flextable/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

most important things are the following: 

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example.
