### ISSUE TITLE
Table caption is on different page than table

### ISSUE THREAD

**Issue by phargarten2** [davidgohel/flextable#393]
For some reason, if the table is long, the caption is separated from the actual table on different pages. 

I modified the example from https://rdrr.io/cran/flextable/man/body_add_flextable.html to include the entirety of mtcars instead of just the first few observations. 

```{r}
library(officer)
library(flextable)

# autonum for caption
autonum <- run_autonum(seq_id = "tab", bkm = "mtcars")

ftab <- flextable( mtcars ) 
ftab <- set_caption(ftab, caption = "mtcars data", autonum = autonum)
ftab <- autofit(ftab)
doc <- read_docx()
doc <- body_add_flextable(doc, value = ftab)
fileout <- tempfile(fileext = ".docx")
fileout <- "test.docx" # uncomment to write in your working directory
print(doc, target = fileout)
```
I get this result:

![Screenshot 2022-04-05 162710](https://user-images.githubusercontent.com/17706062/161843263-6a2736b6-c708-4014-abca-ec387a13d1f0.png)

I would like the table to be underneath the caption and go onto the next page if possible.  I do realize that this may be a Word issue.

One further note: I used `body_add_flextable()` for the purposes of this example but I usually knit the flextables in a Rmarkdown document. 

Session Info 
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042), RStudio 2021.9.0.351

 Locale: LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3     bslib_0.3.1         cpp11_0.4.2         data.table_1.14.2   digest_0.6.29       evaluate_0.15      
  fastmap_1.1.0       **flextable_0.7.1.005** fs_1.5.2            gdtools_0.2.4       glue_1.6.0          graphics_4.1.1     
  grDevices_4.1.1     highr_0.9           htmltools_0.5.2     jquerylib_0.1.4     jsonlite_1.8.0      knitr_1.38.1       
  magrittr_2.0.1      methods_4.1.1     **officer_0.4.2**       R6_2.5.1            rappdirs_0.3.3      Rcpp_1.0.8.3       
  rlang_1.0.2         rmarkdown_2.13.3    sass_0.4.1          stats_4.1.1         stringi_1.7.6       stringr_1.4.0      
  systemfonts_1.0.4   tinytex_0.38.1      tools_4.1.1         utils_4.1.1         uuid_1.0.4          xfun_0.30          
  xml2_1.3.3          yaml_2.3.5          zip_2.2.0         
```

When submitting a new issue:

- [X] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [X] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [X] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [X] Make sure you searched in the *open* and *closed* issues on the github repository.

**Comment by davidgohel** [comment]
I think you need to play with parameter "keepnext", `body_add_flextable(..., keepnext = FALSE)` or `ft.keepnext = TRUE` in a knitr chunk. It's about setting the Word parameter "Keep with next" in paragraph settings.
 
See [#359](https://github.com/davidgohel/flextable/issues/359#issuecomment-997411086)

By default, flextable use "Keep with next". It means that by default Word will try to gather the flextable with the next content on the same page. 

For a single long table with a caption, I would use `keepnext = FALSE`. The example you are using is specific because it only contains a caption and a long table.  The following example is good to understand how to use `keepnext`, you can set it to FALSE and you will see how Word is changing the layout.


```r
library(officer)
library(flextable)

# autonum for caption
autonum <- run_autonum(seq_id = "tab", bkm = "mtcars")

long_str <- rep("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu suscipit neque, a laoreet nulla. Ut risus nunc, dapibus nec commodo id, dignissim sit amet nunc. Vestibulum aliquam blandit neque, vitae maximus justo molestie et. Aliquam facilisis, justo sed consequat blandit, lorem mauris dictum leo, sed finibus sem purus id tortor. In placerat, tellus ut porttitor cursus, massa quam imperdiet nulla, gravida vulputate neque dui vel libero. Fusce lobortis malesuada massa et faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.", 
                6)
long_str <- paste0(long_str, collapse = " ")
ftab <- flextable(head(mtcars) ) 
ftab <- set_caption(ftab, caption = "mtcars data", autonum = autonum)
ftab <- autofit(ftab)
doc <- read_docx()
doc <- body_add_par(doc, value = long_str)
doc <- body_add_flextable(doc, value = ftab, keepnext = TRUE, topcaption = FALSE)
doc <- body_add_par(doc, value = long_str)
fileout <- tempfile(fileext = ".docx")
fileout <- "test.docx" 
print(doc, target = fileout)
browseURL(fileout)
```

> result with `keepnext = TRUE`

<img width="1181" alt="Capture d’écran 2022-05-04 à 19 12 58" src="https://user-images.githubusercontent.com/4331618/166742548-9ebe35c1-7914-4c1d-9175-dab5716ddc71.png">

> result with `keepnext = FALSE`

<img width="1196" alt="Capture d’écran 2022-05-04 à 19 13 16" src="https://user-images.githubusercontent.com/4331618/166742606-7904a9a5-b353-4c81-a047-8c22c21fbad3.png">

**Comment by phargarten2** [comment]
Thank you for letting me know about the argument and this feature in `**flextable**.  

When you said this
> "I think you need to play with parameter "keepnext", `body_add_flextable(..., keepnext = FALSE)` or `ft.keepnext = TRUE` "
I think you meant
`body_add_flextable(..., keepnext = FALSE)` or `ft.keepnext = FALSE`

I would like to give to you my apologies for not finding a duplicate issue; I appreciate that you brought it to my attention.  

Thank you for allowing more context about this option "Keep with next" and where to find it. I didn't even know if that was a possibility. I can see the utility of this option.

**Comment by acid-bbq** [comment]
I use `flextable 0.8.2` and `ft.keepnext=FALSE` has no effect when using it with knitr. After some tests, `ft.keepnext` works until version `0.8.0`. I tried both `bookdown `and `officedown `to compile the doc. With `bookdown`, it is fine to use version `0.8.0`, but with `officedown`, it is a problem because of `set_caption`. 

Reproducible code below.

Thanks

```

> ---
> title: "This is the title of the document"
> author: This is the name of the author
> date: 'This is the date'
> output:
>   officedown::rdocx_document:
>     toc: true
>     toc_depth: 2
>     number_sections: false
>   bookdown::word_document2:
>     toc: true
>     toc_depth: 2
>     toc_float: true
>     number_sections: false
>   word_document: default
> ---
>   
> ```{r setup, include=FALSE}
> # Uncomment for the desired version.
> # flextable.package <- "https://cran.r-project.org/src/contrib/Archive/flextable/flextable_0.8.0.tar.gz"
> # flextable.package <- "https://cran.r-project.org/src/contrib/Archive/flextable/flextable_0.8.1.tar.gz"
> # install.packages(flextable.package, repos=NULL, type="source")
> # install.packages("flextable") ## This is version 0.8.2.
> knitr::opts_chunk$set(echo = TRUE)
> library(knitr)
> library(flextable)
> library(officer)
> library(officedown)
> library(bookdown)
> ```
> 
> # This is a section with ft.keepnext=FALSE
> 
> Table \@ref(tab:tabintro2) shows some text for this section which is stored in a table bekiw with some columns and rows fdsf fdsf sdaf dfs dfsda ff sf saf gregregewr gregrew grew trewtrete tret tretretre
> 
> ```{r sec2, echo=FALSE, ft.keepnext=FALSE}
> ft <- flextable(iris[1:50,])
> ft <- set_caption(ft, caption = "This is a long caption dsa dsad sad sadsa dsa dsa dsa das dsa ds safdsfasdfasdf fdsfsda fdsa",
>                   style = "Table Caption", autonum = run_autonum(seq_id = "tab", bkm = "tabintro2"))
> ft <- autofit(ft)
> ft
> ```

```

**Comment by davidgohel** [comment]
@acid-bbq I think it is fixed in the dev version. Sorry for the inconvenient. We now set the default value to FALSE as it is generating more pain than benefit for the majority of users. Note it is better to open new issue than iterating on closed issues - as we are looking at "open issues", we can easily forget a comment made on a closed issue :)

**Comment by acid-bbq** [comment]
OK thanks, I will give it a try. And is it planned to be implemented soon in a new release? And thank you for the tip about questions!
