### ISSUE TITLE
Histogram (as bar chart) in plot_chunk function

### ISSUE THREAD

**Issue by kotliary** [davidgohel/flextable#423]
I think this is a missing feature in this function. It would be great to be able to add histogram plots to a flextable.

**Comment by davidgohel** [comment]
(from memory) We did not implement the histogram because "density plot" could replace it and there was a risk of over-complication because of the number of potential parameters; the functions `plot_chunk()` and `gg_chunk()` are here to let you make the graphs you want and can substitute calls to `plot_chunk()`. 

Can you propose a PR?
