### ISSUE TITLE
Specify rows to be or not keep_with_next

### ISSUE THREAD

**Issue by samuel-jobert** [davidgohel/flextable#520]
Hi David,

Thanks for this great package too (with officer) !

For my large tables (> 1 page), I would like to specify where page breaks can split the table.
I made a function to modify body$styles$pars$keep_with_next dataset.
It was really easy as you did all the work so that it functions.

I forked your repo [(samuel-jobert/flextable),](https://github.com/samuel-jobert/flextable) may I make a pull request to your repo ?

Regards.
Samuel.

**Comment by davidgohel** [comment]
Thanks Samuel,

Can you explain what this feature will solve? If I understand correctly, you are proposing a kind of "pagination" feature, am I right? Could you share one result so that I am sure I get what do the new feature?

**Comment by samuel-jobert** [comment]
The idea is that my large table can only break on few specific rows (some rows have to be kept together).
So I first set all "rows" with keep with next = TRUE.
After this I set some of the rows with KWN to FALSE, the table will be able to break at these points according to the content above the table (content is not always the same).
Of course, the table parts between breaks are less than a page.

Here is an very ugly example where I could have done multiple tables (it is for the demo !).
I have a data frame with varying multiple lines per item and I don't want lines of an item to be on different pages.

```
df = data.frame(
	"Items" = c(rep("Item 1", 10), rep("Item 2", 15), rep("Item 3", 25), rep("Item 4", 5), rep("Item 5", 25)),
	 "var_bidon" = seq_len(10 + 15 + 25 + 5 + 25)
)
ft = flextable(df)

# Set all rows keep_with_next to TRUE
ft = ft %>% set_keep_with_next(rows = NULL, value = TRUE)
# Select rows after which the break can append (all lines of an item have to be on the same page)
ft = ft %>% set_keep_with_next(rows = c(10, 10+15, 10+15+25, 10+15+25+5), value = FALSE)

doc = read_docx()
doc = doc %>% body_add_par("")
doc = doc %>% body_add_flextable(ft, keepnext = TRUE, split = FALSE)
print(doc, target = "mon_doc.docx")

```
If you add content before the table, the table will only break between items.

I often needed this feature before. I had to verify my doc tables to be sure they were well displayed.
Now I know I can rely on the breaks.

I hope you find it useful too (and hope this "option" does not already exist !)

**Comment by davidgohel** [comment]
Thanks, this is very interesting indeed (this solves a problem I wanted to tackle since a long time). I can't spend time on that right now, but I will try soon.

**Comment by davidgohel** [comment]
Hello

Again, thanks for your inputs, they have been very useful. 

`keep_with_next()` is now exported. I think it is better to name it `keep_with_next()` instead of `set_keep_with_next` as all other functions that style/change a style property are named with the property they change.

I did not keep your modifications (`  # If some rows have different keep_with_next values (set with function set_keep_with_next), we don't apply the default table keep_with_next to all paragraphs`) but reuse your logic in a new function named `paginate()`, your implementation is corresponding to the parameter `hdr_ftr`:

> if TRUE (default), prevent breaks between table body and header and between table body and footer.

Usage of `x$properties$opts_word$keep_with_next` was conflicting with your suggestions: we get much more control over the pages breaks, so `x$properties$opts_word$keep_with_next` is been defunct in favor of `paginate()` and or `keep_with_next()`.
