### ISSUE TITLE
"padding" or "line_spacing" options to PDF

### ISSUE THREAD

**Issue by Cidree** [davidgohel/flextable#530]
Hello,

I am trying to fit my table to one page, but the "padding" and "line_spacing" options are not working when I render my document. However, as you can see in the image, the output seen in the chunk has the effects applied. I do not know if the bug could be related to Quarto, or maybe there is another option to apply what I would like to do.

![flextableError](https://user-images.githubusercontent.com/96820235/227925019-eb7c6af1-cfe8-4ed0-94a0-259ee4624e1a.png)

**Comment by davidgohel** [comment]
as indicated in the documentation (here: https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#pdf-output), "padding" and "line_spacing" are not supported in PDF

> Some features are not implemented in PDF due to technical infeasibility. These are the padding, line_spacing and height properties.

You can set instead of  line_spacing `ft.arraystretch` (height of each row relative to its default height, the default value is 1.5.)

For padding, replace with `ft.tabcolsep`
