### ISSUE TITLE
Flextable in Quarto 1.4 produces corrupt documents

### ISSUE THREAD

**Issue by BMC1986** [davidgohel/flextable#578]
Firstly, great to see the crossrefs of Quarto being implemented.

However, now when rendering to quarto with a flextable object I get a corrupt document with the warning of "Word found unreadable content ...". The contents all seem fine if you recover the doc.

Cann reproduce here.

``````
---
title: "FlextableBug"
format: docx
---

## Quarto


```{r}
#| label: tbl-Biology
#| tbl-cap: A nice caption
#| echo: false


library(flextable)

ft <- flextable(head(mtcars))
ft

```
``````

![image](https://github.com/davidgohel/flextable/assets/115600627/b6727d31-8351-43ec-8b43-1f6051a03c2b)

**Comment by davidgohel** [comment]
Sorry, we did not change anything about Word quarto captions, we stopped doing anything about it a long time ago. If you look at the code, you can check it: https://github.com/davidgohel/flextable/blob/master/R/printers.R#L275

For all related "Quarto caption" related issues:

- we can't do anything about it, Quarto itself is supposed to do it
- we only are looking at the quarto 1.3, when 1.4 will be almost released we will look at it, etc. It seems to me Quarto 1.4 is far from being ready:

<img width="779" alt="Capture d’écran 2023-10-13 à 07 12 18" src="https://github.com/davidgohel/flextable/assets/4331618/1e7c234d-44c6-4826-b8d7-d134b94438ff">

- the quarto product is actively developed and evolve quickly since more than 2 years now, let's be patient as the team advised. 

 You should instead open an issue in Quarto repo.

**Comment by davidgohel** [comment]
This issue can be closed, it is now working as expected with Quarto `1.4.549`
