### ISSUE TITLE
Table is created at the end of word document

### ISSUE THREAD

**Issue by mmoralesIG** [davidgohel/flextable#611]
I recently updated to 0.9.4, and one of the many tables that I'm creating inside a word document is created at the end of the document, when in the code is created almost at the beginning of the document . Funny thing it's not the first table nor the last one.

**Comment by davidgohel** [comment]
When submitting a new issue, please provide the code that is producing the error, it has to be a minimal reproducible example.

**Comment by davidgohel** [comment]
The issue is close because we can't reproduce anything and you did not make any effort to let us reproduce your issue. This is written when you open a new issue so you decided to not follow requirements. 

<img width="1054" alt="Capture d’écran 2024-03-05 à 23 31 11" src="https://github.com/davidgohel/flextable/assets/4331618/85e62830-ee5e-48e5-aba6-02de2e500a55">

When someone reports a bug without providing a concrete example or detailed reproduction of the issue, it becomes extremely difficult, if not impossible, for other contributors or developers to understand and effectively resolve the reported problem. Without an example, it's challenging to identify the exact source or nature of the bug, making the debugging and correction process much more complex and inefficient. Giving a thumbs-down reaction to the closure of the issue is perceived as a lack of cooperation and understanding of the problem-solving processes.
