### ISSUE TITLE
Feature request: expressions (subscript, superscript, etc.) in flextables and stopping tables from breaking across pages

### ISSUE THREAD

**Issue by sybrnorox** [davidgohel/flextable#77]
Hello there,

still very much liking this package and using it a lot, so thanks a lot for it! 

There are two things that I sorely miss, though:

1) Expressions in text within the tables. Basically I would like to be able to use subscript, superscipt and mathematical symbols within tables.

2) Table rows break across pages in MS Word. In MS Word this can be stopped by unselecting 'Allow row to break across pages' in table properties and selecting 'Keep with next' in paragraph properties for the table. 

If any or both of could possibly be implemented it would make me really very happy

Cheers,
Jan

**Comment by davidgohel** [comment]
> For the point 1

These options are already available by using function `display` and `fp_text(vertical_align="superscript")` or `fp_text(font.family="AMathFont")`. But equations (as generated by latex instructions) are not available (because it's a huge work to bring that feature).

> For the point 2

OK, I will find a way to implement that feature later :)

David

**Comment by davidgohel** [comment]
Hi

I `rmarkdown::word_document, you can now set chunk option `ft.split=TRUE` to activate Word option 'Allow row to break across pages'. The option is also available in `body_add_flextable` with argument `split`.
