### ISSUE TITLE
Selecting subset of a flextable

### ISSUE THREAD

**Issue by rbratslaver** [davidgohel/flextable#95]
Hi - is it possible to select certain rows/columns of a flextable object? i.e. as in df[1:10, 3:4]. I see that it gets stored as a list but wasn't sure if there was a way to do this kind of indexing. 

I'm really just trying to find a way to preview the first few rows of my flextable output without having to render the whole table. 

Thanks for your time on this.

**Comment by davidgohel** [comment]
Hi,

No, that's not a feature. I recommend using `head()` on the dataset instead.

David

**Comment by dvanic** [comment]
Hi David, I came to this question and can see your resounding "no" - but think it's possibly a useful feature?

The use case is quite simple: I've got a large summary table (generated from a mix of gtsummary and some custom functions that calculated appropriate statistics) that is in my rmarkdown report, formatted with flextable. I'd like to be able to export into Word, for eventual publication, as this is what journals expects. Exporting the whole thing results in most of the table being outside of the visible page range - so I end up having to copy-paste parts of the table into multiple docx to generate the tables I need.

doing 
save_as_docx(myflextable[,1:10])
save_as_docx(myflextable[,c(1,11:20)] )

would be a lot more reproducible/concise than generating the table (and formatting!) for the full table for the Rmd and its parts for the word.

Is this feature a complete impossibility?

**Comment by RemPsyc** [comment]
I agree, I have the same use case. I apply a bunch of formatting to the original table as a flextable, then only need subsets of the very large table. Right now the workaround is to copy the very long code for each possible subset to keep the same complex formatting.

**Comment by davidgohel** [comment]
Nobody shown any code that could be commented (which is asked when you open a new issue). I hope this won't end with a pointer to the documentation.

The only bit of code is given by @dvanic but not reproducible

```
myflextable[,c(1,11:20)]
```

It seems she formatted at least 20 columns, but only need 3 columns... Why not using `col_keys` argument of flextable and only build the flextable for these 3 columns? Why is it necessary for me to implement a new system so that you can avoid using existing parameter `col_keys` or `head`? 

@RemPsyc can't you provide an example? A **minimal and reproducible** example.

**Comment by davidgohel** [comment]
Nobody shown any code that could be commented (which is asked when you open a new issue). I hope this won't end with a pointer to the documentation.

The only bit of code is given by @dvanic but not reproducible

```
myflextable[,c(1,11:20)]
```

It seems she formatted at least 20 columns, but only need 3 columns... Why not using `col_keys` argument of flextable and only build the flextable for these 3 columns? Why is it necessary for me to implement a new system so that you can avoid using existing parameter `col_keys` or `head`? 

@RemPsyc can't you provide an example? A **minimal and reproducible** example.

**Comment by RemPsyc** [comment]
Thank you for the clarification David and I'll try my best to provide a minimal and reproducible example.

Let's assume this is the original table:

```
library(flextable)
library(dplyr)

# Make one table (assuming many more columns)
ft <- flextable(head(mtcars)) %>%
  bold(i = 2) # Assuming much more formatting at this step
ft
```
For purposes of presentation of a research report, we need to split the numerous columns in two tables (but assume many more). So one way to do it is repeating the full code from the beginning as many times as needed through `col_keys` or direct subsetting of the dataframe, e.g.:

```
# First table
ft <- flextable(head(mtcars),
                col_keys = c("mpg", "cyl", "disp", "drat", "wt")) %>%
  bold(i = 2) # Assuming much more formatting at this step
ft

# Duplicate code to make second table
ft <- flextable(head(mtcars),
                col_keys = c("qsec", "vs", "am", "gear", "carb")) %>%
  bold(i = 2) # Assuming much more formatting at this step
ft

# Again for third, etc. table
# [...]

```

The desired solution would (for instance) allow redefining `col_keys`:

```
ft <- flextable(head(mtcars)) %>%
  bold(i = 2) # Assuming much more formatting at this step
ft

ft$col_keys <- c("mpg", "cyl", "disp", "drat", "wt")
```
Though of course currently, it outputs an error when trying to run `ft` after making this change:
```
ft
Error in data.frame(col_id = x$col_keys, width = x[[part]]$colwidths,  : 
                      arguments imply differing number of rows: 5, 11

```
Alternatively, if we could redefine the `col_keys` by feeding the `flextable()` function a `flextable` object instead of a dataframe:

```
ft <- flextable(ft, col_keys = c("qsec", "vs", "am", "gear", "carb"))
# Formatting has already been done on the existing ft object
```
Though right now `flextable` objects arent accepted:
```
ft
Error in flextable(ft, col_keys = c("qsec", "vs", "am", "gear", "carb")) : 
is.data.frame(data) is not TRUE

```
In any case, it is not a functional issue, it would just purely be a DRY quality of life upgrade to make code more concise. Perhaps there is already a way to do so that I have missed?

**Comment by davidgohel** [comment]
There is nothing to do but use R control structures to iterate over your data subsets. You can use for loops, the purrr package, or more simply use the `mapply()` or `lapply()` functions. Something like:

1. Split your data - one element for one subset
2. Use flextable on each subset

----
About your specific requests:

> `ft$col_keys <- c("mpg", "cyl", "disp", "drat", "wt")`

Element `col_keys` is read-only. Read the documentation, you will not see anywhere users are invited to manipulate this compound in the object. 

> Alternatively, if we could redefine the col_keys by feeding the flextable() 
> function a flextable object instead of a dataframe:

we can't

**Comment by RemPsyc** [comment]
Thanks for looking into it David. Another alternative perhaps would be to indeed follow your suggestion of splitting the data with a function, then in lapply, use a custom function containing all of the flextable formatting required. I think this is as concise it will get.
